config/routes.rb
Rails.application.routes.draw do
  resources :vacation_itineraries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "vacation_itineraries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vacation_itinerary.rb
class VacationItinerary < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vacation_itineraries_controller.rb
class VacationItinerariesController < ApplicationController
  before_action :set_vacation_itinerary, only: [:show, :edit, :update, :destroy]

  # GET /vacation_itineraries
  # GET /vacation_itineraries.json
  def index
    @vacation_itineraries = VacationItinerary.all
  end

  # GET /vacation_itineraries/1
  # GET /vacation_itineraries/1.json
  def show
  end

  # GET /vacation_itineraries/new
  def new
    @vacation_itinerary = VacationItinerary.new
  end

  # GET /vacation_itineraries/1/edit
  def edit
  end

  # POST /vacation_itineraries
  # POST /vacation_itineraries.json
  def create
    @vacation_itinerary = VacationItinerary.new(vacation_itinerary_params)

    respond_to do |format|
      if @vacation_itinerary.save
        format.html { redirect_to @vacation_itinerary, notice: 'Vacation itinerary was successfully created.' }
        format.json { render :show, status: :created, location: @vacation_itinerary }
      else
        format.html { render :new }
        format.json { render json: @vacation_itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacation_itineraries/1
  # PATCH/PUT /vacation_itineraries/1.json
  def update
    respond_to do |format|
      if @vacation_itinerary.update(vacation_itinerary_params)
        format.html { redirect_to @vacation_itinerary, notice: 'Vacation itinerary was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation_itinerary }
      else
        format.html { render :edit }
        format.json { render json: @vacation_itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacation_itineraries/1
  # DELETE /vacation_itineraries/1.json
  def destroy
    @vacation_itinerary.destroy
    respond_to do |format|
      format.html { redirect_to vacation_itineraries_url, notice: 'Vacation itinerary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation_itinerary
      @vacation_itinerary = VacationItinerary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_itinerary_params
      params.require(:vacation_itinerary).permit(:location, :start_date, :end_date, :travel_time, :name, :description, :need_vaccins)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vacation_itineraries_helper.rb
module VacationItinerariesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vacation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vacation_itineraries/_form.html.erb
<%= form_for(vacation_itinerary) do |f| %>
  <% if vacation_itinerary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vacation_itinerary.errors.count, "error") %> prohibited this vacation_itinerary from being saved:</h2>

      <ul>
      <% vacation_itinerary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

  <div class="field">
    <%= f.label :travel_time %>
    <%= f.number_field :travel_time %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :need_vaccins %>
    <%= f.check_box :need_vaccins %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacation_itineraries/edit.html.erb
<h1>Editing Vacation Itinerary</h1>

<%= render 'form', vacation_itinerary: @vacation_itinerary %>

<%= link_to 'Show', @vacation_itinerary %> |
<%= link_to 'Back', vacation_itineraries_path %>

app/views/vacation_itineraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacation Itineraries</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Travel time</th>
      <th>Name</th>
      <th>Description</th>
      <th>Need vaccins</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacation_itineraries.each do |vacation_itinerary| %>
      <tr>
        <td><%= vacation_itinerary.location %></td>
        <td><%= vacation_itinerary.start_date %></td>
        <td><%= vacation_itinerary.end_date %></td>
        <td><%= vacation_itinerary.travel_time %></td>
        <td><%= vacation_itinerary.name %></td>
        <td><%= vacation_itinerary.description %></td>
        <td><%= vacation_itinerary.need_vaccins %></td>
        <td><%= link_to 'Show', vacation_itinerary %></td>
        <td><%= link_to 'Edit', edit_vacation_itinerary_path(vacation_itinerary) %></td>
        <td><%= link_to 'Destroy', vacation_itinerary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacation Itinerary', new_vacation_itinerary_path %>

app/views/vacation_itineraries/new.html.erb
<h1>New Vacation Itinerary</h1>

<%= render 'form', vacation_itinerary: @vacation_itinerary %>

<%= link_to 'Back', vacation_itineraries_path %>

app/views/vacation_itineraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @vacation_itinerary.location %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @vacation_itinerary.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @vacation_itinerary.end_date %>
</p>

<p>
  <strong>Travel time:</strong>
  <%= @vacation_itinerary.travel_time %>
</p>

<p>
  <strong>Name:</strong>
  <%= @vacation_itinerary.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vacation_itinerary.description %>
</p>

<p>
  <strong>Need vaccins:</strong>
  <%= @vacation_itinerary.need_vaccins %>
</p>

<%= link_to 'Edit', edit_vacation_itinerary_path(@vacation_itinerary) %> |
<%= link_to 'Back', vacation_itineraries_path %>